os: linux
dist: xenial
language: php

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql
  - postgresql

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

before_install:
  # Prepare MySQL schema
  - mysql < ./tests/Fixtures/mysql.sql
  - mysql < ./examples/examples.sql
  - mysql -e "SET PASSWORD = PASSWORD('password');"
  # Prepare Sqlite schema
  - sqlite3 tests/Fixtures/sqlite.db < tests/Fixtures/sqlite.sql
  # Prepare postgresql
  - psql -U postgres -d postgres -f tests/Fixtures/postgres.sql

install:
  - composer install --prefer-dist
  # Bump the version
  - ./scripts/bump-version ${TRAVIS_BRANCH}

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit --coverage-clover=coverage.xml
  - make analyse
  - php bin/schemarkdown.php --config-file=tests/Fixtures/database.php
  - make clean schemarkdown.phar VERSION=${TRAVIS_BRANCH}

after_success:
  - if [[ "7.1" == "${TRAVIS_PHP_VERSION}" ]]; then bash <(curl -s https://codecov.io/bash) ; fi

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor

deploy:
  provider: releases
  token: ${GITHUB_ACCESS_TOKEN}
  file: schemarkdown.phar
  skip_cleanup: true
  on:
    tags: true
    php: 7.1
